### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by pedela** [rwth-acis/FreePastry#2]
The readme of this project was never updated and still is an HTML file stating the latest release being 2.2.1.

Please create a new Readme in Markdown format on the top level of the project that briefly states, that this is a fork of the original project, used in las2peer with the [..] changes compared to the original.

Thanks ;-)

**Comment by Aran30** [comment]
Is done as of commit [c78b6e8](https://github.com/rwth-acis/FreePastry/commit/c78b6e8fed3b44e959e3b3e9c47a8b73d869f2d9) ;).
